// Scale families, defined by their step pattern (semitones between successive degrees,
// wrapping back to the octave). Modes of a rotatable family are generated by rotating the
// step pattern so each degree in turn becomes the new root ("diatonic" / "modal" scales).
// Symmetric scales are listed directly, since rotating them doesn't produce new pitch
// content ("nondiatonic" scales).
const FAMILIES = [
  {
    key: 'diatonic',
    label: 'Diatonic Modes',
    steps: [2, 2, 1, 2, 2, 2, 1],
    modeNames: ['Ionian', 'Dorian', 'Phrygian', 'Lydian', 'Mixolydian', 'Aeolian', 'Locrian'],
  },
  {
    key: 'melodicMinor',
    label: 'Melodic Minor Modes',
    steps: [2, 1, 2, 2, 2, 2, 1],
    modeNames: [
      'Melodic Minor', 'Dorian ♭2', 'Lydian Augmented', 'Lydian Dominant',
      'Mixolydian ♭6', 'Locrian ♮2', 'Altered',
    ],
  },
  {
    key: 'harmonicMinor',
    label: 'Harmonic Minor Modes',
    steps: [2, 1, 2, 2, 1, 3, 1],
    modeNames: [
      'Harmonic Minor', 'Locrian ♮6', 'Ionian ♯5', 'Dorian ♯4',
      'Phrygian Dominant', 'Lydian ♯2', 'Super Locrian 𝄫7',
    ],
  },
  {
    key: 'symmetric',
    label: 'Symmetric / Nondiatonic',
    fixed: [
      { name: 'Whole Tone', steps: [2, 2, 2, 2, 2, 2] },
      { name: 'Diminished (W-H)', steps: [2, 1, 2, 1, 2, 1, 2, 1] },
      { name: 'Diminished (H-W)', steps: [1, 2, 1, 2, 1, 2, 1, 2] },
    ],
  },
];

// Cumulative semitone offsets from the root, one per scale degree (degree 0 is always 0).
function stepsToDegrees(steps) {
  const degrees = [0];
  let sum = 0;
  for (const s of steps.slice(0, -1)) {
    sum += s;
    degrees.push(sum);
  }
  return degrees;
}

function rotate(arr, n) {
  return [...arr.slice(n), ...arr.slice(0, n)];
}

// Build the "chord implied by the scale" by stacking every other scale degree
// (1-3-5-7-9-11-13...), deduping as the stack wraps back onto pitch classes it
// already used (this happens naturally, and correctly, for symmetric scales).
function scaleToChordIntervals(degrees) {
  const len = degrees.length;
  const seen = new Set();
  const chord = [];
  for (let i = 0; i < len; i++) {
    const degree = degrees[(i * 2) % len];
    if (!seen.has(degree)) {
      seen.add(degree);
      chord.push(degree);
    }
  }
  return chord;
}

export const SCALE_TYPES = FAMILIES.flatMap((family) => {
  if (family.fixed) {
    return family.fixed.map(({ name, steps }) => {
      const degrees = stepsToDegrees(steps);
      return {
        key: `${family.key}:${name}`,
        // A non-breaking hyphen (not the plain ASCII "-" from `name`, which stays as-is
        // since it's also the identity key's suffix) — otherwise "(W-H)"/"(H-W)" are
        // fair game for the browser to split right at the hyphen when wrapping, landing
        // "(W-" on one line and "H)" on the next.
        label: name.replace(/-/g, '‑'),
        category: family.label,
        degrees,
        chordIntervals: scaleToChordIntervals(degrees),
      };
    });
  }
  return family.modeNames.map((name, i) => {
    const degrees = stepsToDegrees(rotate(family.steps, i));
    return {
      key: `${family.key}:${name}`,
      label: name,
      category: family.label,
      degrees,
      chordIntervals: scaleToChordIntervals(degrees),
      // Which degree of the parent scale this mode starts on (Ionian=1, Dorian=2, ...) —
      // a real ordering, not decoration, so the UI can list these as a numbered set.
      degreeIndex: i + 1,
      // These are the "modal" families — each mode has a real (if sometimes unusual)
      // major/minor-flavored key signature. Symmetric scales (whole tone, diminished)
      // don't sit "in a key" at all, so they're left unmarked.
      hasKeySignature: true,
    };
  });
});
